name: Run Tests

on: [pull_request]

jobs:
  test_lints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Load node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install node_modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Test SASS
        run: npm run test:sass
        
      - name: Test JS
        run: npm run test:js

  test_cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Run backend container
        run: docker-compose -f "docker-compose.test.yml" up -d --build

      - name: Create config.json
        run: echo $TEST_CONFIG_JSON > src/config.json
        env:
          TEST_CONFIG_JSON: "{ \"apiURL\": \"http://localhost:1337\", \"APP_ENV\": \"prod\" }"

      - name: Test Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
